//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Step> Step { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<CompletedRequests> CompletedRequests { get; set; }
        public virtual DbSet<NotCompletedRequests> NotCompletedRequests { get; set; }
        public virtual DbSet<NewRequests> NewRequests { get; set; }
        public virtual DbSet<WorkingRequests> WorkingRequests { get; set; }
    }
}
