//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public Nullable<int> NewRequestsId { get; set; }
        public Nullable<int> WorkingRequestId { get; set; }
        public string Name { get; set; }
        public string StepDetail { get; set; }
        public Nullable<bool> Checkedd { get; set; }
        public Nullable<int> CompletedRequestsId { get; set; }
        public Nullable<int> NotCompletedRequestsId { get; set; }
    
        public virtual CompletedRequests CompletedRequests { get; set; }
        public virtual NotCompletedRequests NotCompletedRequests { get; set; }
        public virtual NewRequests NewRequests { get; set; }
        public virtual WorkingRequests WorkingRequests { get; set; }
    }
}
